# Generated by Django 5.2.5 on 2025-08-18 00:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='temps/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('PY', 'PYTHON'), ('JS', 'JAVA SCRIPT'), ('C#', 'C SHARP'), ('TS', 'TYPE SCRIPT')], max_length=2)),
            ],
        ),
    ]
