# Generated by Django 5.2.5 on 2025-08-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
